services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: charene-menu
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
